services:
    app.admin:
        class: AppBundle\Admin\AppAdmin
        arguments: ['%sulu_admin.name%']
        tags:
            - {name: 'sulu.admin'}
            - {name: 'sulu.context', context: 'admin'}

    app.content_navigation.pages:
        class: AppBundle\Admin\PagesNavigationProvider
        tags:
            - {name: 'sulu_admin.content_navigation', alias: 'pages'}
            - {name: 'sulu.context', context: 'admin'}

    app.content.types:
        class: AppBundle\Content\Types\ContentTypePool
        calls:
            - ['addType', ['text_line', '@app.content.types.text_line']]
            - ['addType', ['text_editor', '@app.content.types.text_editor']]

    app.content.types.text_line:
        class: AppBundle\Content\Types\ScalarContentType

    app.content.types.text_editor:
        class: AppBundle\Content\Types\ScalarContentType

    app.repository.page:
        class: AppBundle\Entity\PageRepository
        factory: ['@doctrine.orm.entity_manager', getRepository]
        arguments: ['AppBundle:Page']

    app.repository.excerpt:
        class: AppBundle\Entity\ExcerptRepository
        factory: ['@doctrine.orm.entity_manager', getRepository]
        arguments: ['AppBundle:Excerpt']

    app.serializer.page:
        class: AppBundle\Serializer\PageSubscriber
        tags:
            - { name: 'jms_serializer.event_subscriber' }
